<?php
require_once (YII_ZII_PATH.'/widgets/CMenu.php');

/** 
 * @author armen bablanyan
 * This class overide CMenu class for initilizing menus from Database 
 * Some functions of CMenu class also overided for passing slag from url.
 */
class AMenu extends CMenu {
	
	/**
	 * Initializes the menu widget from DB.
	 * This method mainly normalizes the {@link items} property by invoking parent method.
	 */
	public function init()
	{
		$this->getDBMenu();
		parent::init();
	}
	
	/**
	 * Checks whether a menu item is active.
	 * This is done by checking if the currently requested URL is generated by the 'url' option
	 * of the menu item. Note that the GET parameters not specified in the 'url' option will be ignored.
	 * @param array $item the menu item to be checked
	 * @param string $route the route of the current request
	 * @return boolean whether the menu item is active
	 */
	protected function isItemActive($item,$route)
	{
		if(isset($item['url']) && is_array($item['url']) && !strcasecmp(trim($item['url'][0],'/'),$route))
		{
			if(count($item['url'])>1)
			{
				foreach(array_splice($item['url'],1) as $name=>$value)
				{
					//it's seems to don't check slag for checking please use this if(!isset($_GET[$name]) || $_GET[$name]!=$value)
					if(!isset($_GET[$name]) || ($name != 'slag' && $_GET[$name]!=$value))
						return false;
				}
			}
			return true;
		}
		return false;
	}
	
	/**
	 * This method is fetching menu items from database and initializs property of items
	 */
	protected function getDBMenu()
	{
		
		$c = new CDbCriteria();
		$c->together = true;
		$c->with = array('lng', 'menu');
		$c->condition = 'lng.lng_code=:lng and menu.menu_status=:stat';
		$c->params = array(':lng'=>Yii::app()->language, ':stat'=>1);
		$c->order = "menu.menu_order";
		
		$menus = MenuDetails::model()->findAll($c);
		
		foreach ($menus as $menu){
			if (isset($menu->page_content) && $menu->page_content!=null && ($menu->menu->menu_action=='' || $menu->menu->menu_action=='content')){
				$action = 'site/content';
				$slag = (isset($menu->seo_slag) && $menu->seo_slag!='')?$menu->seo_slag:'index';
				$res[] = array('label'=>$menu->menu_name, 'url'=>array($action, 'pid'=>$menu->menu_id));	
			}
			else {
				$action = ($menu->menu->menu_action!='' && $menu->menu->menu_action!='content')?'site/'.$menu->menu->menu_action:'site/index';
				$res[] = array('label'=>$menu->menu_name, 'url'=>array($action));
			}
		}
		
		$this->items = $res;
		
		/* $this->items = array(
				array('label'=>'Home1', 'url'=>array('site/index')),
				array('label'=>'Search1', 'url'=>array('site/search')),	
				array('label'=>'About', 'url'=>array('site/content', 'pid'=>100, 'slag'=>'index')),
				array('label'=>'Contact1', 'url'=>array('site/contact')),
				array('label'=>'Login1', 'url'=>array('site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout1 ('.Yii::app()->user->name.')', 'url'=>array('site/logout'), 'visible'=>!Yii::app()->user->isGuest)
		); */
	}
	
}

?>